# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b308cffd02b17cb6b051c5969cd6fa90de2b876e157707893f8b9f8ae82d42742a154f4aad110d7840642d84ac000bebf397598502cccf923267c7e9904a1384

test:
  secret_key_base: 74292729fdebe4aa0e6ee62ae491bc781a714692c9059c7d31529ef7a2bec77f47a02d253f8b4d4d40b3cea8e578a15c1849f217b63d60a2ca61dc2186d84279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
